version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask_app
    expose:
      - "5000"
    restart: always
    
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always
