# Use the latest Alpine version as the base image
FROM alpine:latest

# Install dependencies and Nginx with the headers-more module
RUN apk update && apk upgrade
RUN apk add --no-cache \
    nginx \
    nginx-mod-http-headers-more \ 
    && apk cache clean

# Copy custom configuration files
COPY ./../nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./../nginx/nginx-flask.conf /etc/nginx/conf.d/flask.conf

# Expose necessary ports
EXPOSE 80 443

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
